export {createSourceFileGraph} from './01-create-source-file-graph';
export {parseSourceFiles} from './02-parse-source-files';
export {createSymbolDefinitions} from './03-create-symbol-definitions';
export {resolveSymbolReferences} from './04-resolve-symbol-references';
export {resolveConstantValues} from './05-resolve-constant-values';
//export {dealiasSymbols} from './06-dealias-symbols';
export {computeNodeHashes} from './06-compute-node-hashes';
export {checkSemantics} from './07-check-semantics';
export {generateTargetCode} from './08-generate-target-code';
